---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -f Gemfile.lock
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6-nightly BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6-nightly BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6-nightly BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6-nightly BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
    sudo: required
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "RlXD9MDfKavdsjPCtq8XmqXTszraam9oFNJlnd+tryJQ/fN10Q8l36+UcSbxUgBF9Wyy8muyjUiLB9bhje1IQUcsATXpa0YgWdoTIhv18SmIA58a1eXt52TqeLG73aSgu2ZCebc9SkSRV+vNVXcPleIdb9dX8HjsJOGk1sw0jGwDO93nSuInKG2/rl0kevbI5BcY6G+o2dInI4Nknq0nxpzcw8X602j/xak95lLxQmQfaMrXvKUAdp4XuLV8YfbahQhD7bCe4b6hudqVi4/I7Xag8SonX9pMZJzC5J0USjDqG01BQLXAz2KDrjmxf7Hy4KI8BIkZonvjE2dx23NRM28HNDhlcMRV6k9p2SSCR5CZKzwRXOh38OBNL/vpHnpTk5GOEqSMwD8Zt0jJpGNIMR6i4a5fcdBznp3FXqc/28gXduAAn2lGBG4lb8AMJ40J5bgmPYJvoYMxrS2rwfFJ91LYk3UK2wNhbGF772+0sRQi0iyOUEoxa3D0Jkt9PrsYXQ6rxW6dNkkZFGdE0Uni6Mm4mNZkWcK2Ke+wRGSetIv2vyABY5LJinBLjYH8T4LZYrmQ/LALuIhjJWhxXvWA94/brwIXF0Nkou9vEKu6uT+bBHbGPrLmvPkLsnHxGV515M0NTUFCQ8coPpYHgacJkpfTP9IZk7QHFUi3LWNG1VI="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
